#pragma once
#include <memory>
#include <vector>

/**
 * @brief Abstract base class for the quantum system's Hamiltonian.
 * * Defines the interface for evaluating the local energy of the system.
 * Specific physics problems (e.g., interacting vs. non-interacting) will
 * inherit from this class and implement their own energy calculations.
 */
class Hamiltonian {
public:
    // Use the default deconstructor generated by the compiler
    virtual ~Hamiltonian() = default;

    virtual double computeLocalEnergy(
        class WaveFunction&,
        std::vector<std::unique_ptr<class Particle>>&
    ) {
        throw std::invalid_argument("computeLocalEnergy called on base class hamiltonian");
        return -1;
    }

    virtual double getRepulsiveFactor() {
        throw std::invalid_argument("getRepulsiveFactor called on base class hamiltonian");
        return -1;
    }

    virtual double has_hardcore() {
        return false;
    }

    virtual double get_interaction_strength() {
        throw std::invalid_argument("get_hardcore_strength called on base class hamiltonian");
        return -1;
    }

    virtual void set_interaction_strength(double) {
        throw std::invalid_argument("set_hardcore_strenght called on base class hamiltonian");
    }

    virtual void set_percStrength(double) {
        throw std::invalid_argument("set_percStrength called on base class hamiltonian");
    }

    static void set_kinetic_factor(double kin_factor) { s_kinetic_factor = kin_factor; }
    static double get_kinetic_factor() { return s_kinetic_factor; }
protected:
    static double s_kinetic_factor;
};

